#!/bin/bash

header() {
	echo ======= $*
}

install_chrome() {
	header Installing Google Chrome...
	wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O /tmp/google-chrome-stable_current_amd64.deb
	sudo dpkg -i /tmp/google-chrome-stable_current_amd64.deb
}

install_dbeaver() {
	sudo add-apt-repository -u -y ppa:serge-rider/dbeaver-ce # dbeaver (optional dependency)
	sudo apt install -y dbeaver-ce
}

install_dropbox() {
	local RELEASE=$(lsb_release -sc)

	if ! wget -q https://linux.dropboxstatic.com/ubuntu/dists/$RELEASE/ -O /dev/null; then
		echo "NOTE: dropbox hasn't updated their APT repository for $RELEASE, falling back to bionic!"
		RELEASE=bionic
	fi

	sudo add-apt-repository -u -y "deb http://linux.dropbox.com/ubuntu $RELEASE main" # DROPBOX
	# add dropbox GPG key
	sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5044912E
	sudo apt update
	sudo apt install -y dropbox
}

configure_github() {
	header Configure GitHub SSH key...
	mkdir -p ~/.ssh
	cd ~/.ssh
	ssh-keygen -t rsa -C "$GIT_EMAIL" -f ./id_rsa
	cat ./id_rsa.pub
	echo
	echo Add the above public key to your GitHub account: https://github.com/settings/ssh/new
	echo
	read -p "Once complete, press any key to continue..."
}

install_dotfiles() {
	header Configure dotfiles...
	mkdir -p ~/projects
	mkdir -p ~/bin

	if [ ! -d ~/projects/dotfiles ]; then
		git clone git@github.com:$GIT_USERNAME/dotfiles.git ~/projects/dotfiles ||
		  git clone git@github.com:mpareja/dotfiles.git ~/projects/dotfiles
	fi

	cd ~/projects/dotfiles
	./install.sh
}

configure_vim() {
	header About to recreate ~/.vim directory...
	[ -d ~/.vim ] && rm -rI ~/.vim
	git clone git@github.com:$GIT_USERNAME/vim-settings.git ~/.vim ||
	  git clone git@github.com:mpareja/vim-settings.git ~/.vim
	cd ~/.vim

	# NOTE: node is required

	./install.sh
}

install_virtualbox() {
	# add VirtualBox GPG key
	wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
	sudo add-apt-repository -u -y "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -sc) contrib" # VIRTUALBOX

	header Installing latest VirtualBox...
	local APP=$(apt-cache search virtualbox-[0-9] | sort -r | head -1 | cut -d ' ' -f 1)
	sudo apt-get install -y $APP
}

install_plank() {
	header Configuring plank...
	rm ~/.config/plank/dock1/launchers/plank.dockitem
	cp -R plank ~/.config
}

install_docker() {
	curl -sSL https://get.docker.com/ | sudo sh
}

install_n() {
	header Installing n the node version manager...
	git clone git@github.com:tj/n ~/projects/n

	cd ~/projects/n

	sudo make install

	cd -
}

install_nvm() {
	header Installing nvm the node version manager...
	wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
}
