#!/bin/bash
get_workspace() {
	i3-msg -t get_workspaces \
	  | jq '.[] | select(.focused==true).num' \
	  | cut -d"\"" -f2
}

i3-input -F "rename workspace to \"$(get_workspace): %s\"" -P 'New name: '

