#!/bin/bash

set -eou pipefail
# set -x

main() {
  TARGET=${1:-HDMI-0}

  S="-s $(detect_socket)"

  CUR=$(i3-msg $S -t get_workspaces | jq '.[] | select(.focused) | .name' -r)

  i3-msg $S -t get_workspaces | jq -r .[].name | grep -v calendar | while read w; do
    i3-msg $S workspace "$w" >/dev/null
    i3-msg $S move workspace to output "$TARGET" >/dev/null
  done

  i3-msg $S workspace "$CUR" >/dev/null
}

# required when invoked by udev
detect_socket() {
  local THE_USER=$(ps ax -o comm,uid | grep "^i3\s" | awk '{ print $2 }')
  ls /run/user/$THE_USER/i3/ipc-socket* | head -1
}

main "$@"
