#!/bin/bash

set -eou pipefail
#set -x

main() {
  S="-s $(detect_socket)"

  TARGET=${1:-$(i3-msg $S -t GET_OUTPUTS | jq '.[] | select(.rect.width == 3440) | .name' -r)}
  ATTEMPTS=10 # about 5 seconds

  CUR=$(i3-msg $S -t get_workspaces | jq '.[] | select(.focused) | .name' -r)

  workspaces_to_move "$TARGET" | while read w; do
    echo Workspace: $w
    i3-msg $S workspace "$w" >/dev/null
    with_retry move_workspace "$TARGET" || {
      # in case of failure, cleanup
      i3-msg $S workspace "$CUR" >/dev/null
      false
    }
  done

  i3-msg $S workspace "$CUR" >/dev/null
}

workspaces_to_move() {
  i3-msg -s $(detect_socket) -t get_workspaces | jq ".[] | select(.output != \"$1\") | .name" -r | grep -v calendar
}

move_workspace() {
  i3-msg -s $(detect_socket) move workspace to output "$1" >/dev/null
}

# required when invoked by udev
detect_socket() {
  local THE_USER=$(ps ax -o comm,uid | grep "^i3\s" | awk '{ print $2 }')
  ls /run/user/$THE_USER/i3/ipc-socket* | head -1
}

with_retry() {
  local ATTEMPTS=10 # 5 seconds

  for (( i=1; i <= $ATTEMPTS; i++ )); do
    if "$@"; then
      break
    fi

    if [ $i -ge $ATTEMPTS ]; then
      echo "ERROR: exceeded $ATTEMPTS attempts, aborting."
      return 1
    fi

    echo "WARN: error encountered, retrying the following command:"
    echo "  $@"
    sleep 0.5
  done
}

main "$@" # 2>&1 | tee -a /tmp/transition-to-monitor.log
