- name: Install sysctl.d configuration
  become: true
  copy:
    src: sysctl.d/
    dest: /etc/sysctl.d/
    mode: 0644
    owner: root
    group: root
  notify: reload sysctl

- name: '.profile: include global node and dotfiles bins'
  blockinfile:
    dest: /home/{{ ansible_user_id }}/.profile
    marker: '# {mark} ANSIBLE: include global node and dotfiles bins'
    block: |
      if echo ":$PATH:" | grep -qv ":$HOME/projects/dotfiles/bin:" ; then
          PATH="$PATH:$HOME/projects/dotfiles/bin:$HOME/.n/bin"
      fi

- name: '.bashrc: HISTSIZE'
  lineinfile:
    path: /home/{{ ansible_user_id }}/.bashrc
    regexp: '^HISTSIZE=.*'
    line: 'HISTSIZE=10000'

- name: '.bashrc: HISTFILESIZE'
  lineinfile:
    path: /home/{{ ansible_user_id }}/.bashrc
    regexp: '^HISTFILESIZE=.*'
    line: 'HISTFILESIZE=20000'

- name: '.bashrc: configure GITHUB_TOKEN'
  blockinfile:
    dest: /home/{{ ansible_user_id }}/.bashrc
    marker: '# {mark} ANSIBLE: derive GitHub token'
    block: "export GITHUB_TOKEN=$(cat ~/.npmrc | grep '^//npm.pkg.github.com' | sed 's/^.*=\"\\(.*\\)\"/\\1/')"

- name: 'direnv: load in .bashrc'
  blockinfile:
    dest: /home/{{ ansible_user_id }}/.bashrc
    marker: '# {mark} ANSIBLE: load direnv'
    block: 'source <(direnv hook bash)'

- name: 'hosts: enable FQDN to enable sending via gmail'
  become: true
  blockinfile:
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE: enable FQDN to enable sending via gmail"
    block: "127.0.0.1	localhost.localdomain localhost {{ inventory_hostname }}"

- name: 'perf: disable kernel mitigations'
  become: true
  lineinfile:
    path: /etc/default/grub
    regexp: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet.*"'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash mitigations=off"'
  notify: update grub

- name: Install common packages
  become: true
  block:

  - name: Add non-free apt repositories
    become: true
    copy:
      src: apt
      dest: /etc
      mode: 0644
      owner: root
      group: root
    notify: update apt

  # by default, handlers are run after all tasks to avoid duplication, we need it now
  - name: Ensure update apt has run, if necessary
    meta: flush_handlers

  - name: apt install
    apt:
      state: present
      name:
        - apt-listchanges
        - autoconf
        - autogen
        - compizconfig-settings-manager
        - curl
        - direnv
        - dos2unix
        # dmenu is required by dunst actions
        - dmenu
        - dunst
        - filezilla
        - flameshot
        - fonts-liberation
        - fonts-noto-color-emoji
        - fonts-open-sans
        - g++
        - git-delta
        - git-gui
        - gparted
        - hexchat
        - hub
        - i3xrocks-memory
        - i3xrocks-time
        - i3xrocks-volume
        - inotify-tools
        - iotop
        - jq
        - libnotify-bin
        - make
        - meld
        - mesa-utils
        - mitmproxy
        - openssh-server
        - p7zip-full
        - pcmanfm
        - pkgconf
        - playerctl
        - regolith-desktop
        - regolith-session-flashback
        - regolith-look-nord
        - samba
        - silversearcher-ag
        - spotify-client
        - tmux
        - traceroute
        - tree
        - vifm
        - vim-gtk3
        - wireshark
        - wmctrl
        - x11vnc
        - xclip
        - xdotool
        - xfonts-terminus

  # we use dunst and don't know how to prevent installation above
  - name: apt remove regolith-rofication
    apt:
      state: absent
      name: regolith-rofication
