- name: Install sysctl.d configuration
  become: true
  copy:
    src: sysctl.d/
    dest: /etc/sysctl.d/
    mode: 0644
    owner: root
    group: root
  notify: reload sysctl

- name: '.profile: include global node and dotfiles bins'
  blockinfile:
    dest: /home/{{ ansible_user_id }}/.profile
    marker: '# {mark} ANSIBLE: include global node and dotfiles bins'
    block: 'PATH="$PATH:$HOME/n/bin:$HOME/projects/dotfiles/bin"'

- name: '.bashrc: configure GITHUB_TOKEN'
  blockinfile:
    dest: /home/{{ ansible_user_id }}/.bashrc
    marker: '# {mark} ANSIBLE: derive GitHub token'
    block: "export GITHUB_TOKEN=$(cat ~/.npmrc | grep '^//npm.pkg.github.com' | sed 's/^.*=\"\\(.*\\)\"/\\1/')"

- name: 'hosts: enable FQDN to enable sending via gmail'
  become: true
  blockinfile:
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE: enable FQDN to enable sending via gmail"
    block: "127.0.0.1	localhost.localdomain localhost {{ inventory_hostname }}"

- name: Install common packages
  become: true
  apt:
    state: present
    name:
      - apt-listchanges
      - autoconf
      - autogen
      - compizconfig-settings-manager
      - curl
      - dos2unix
      - dunst
      - filezilla
      - flatpak
      - gnome-software-plugin-flatpak
      - fonts-noto-color-emoji
      - g++
      - gconf2
      - git-gui
      - gparted
      - hexchat
      - hub
      - i3xrocks-volume
      - inotify-tools
      - iotop
      - jq
      - maim
      - make
      - meld
      - mesa-utils
      - mitmproxy
      - libnotify-bin
      - openssh-server
      - p7zip-full
      - pkgconf
      - pcmanfm
      - pinta
      - playerctl
      - regolith-desktop
      - regolith-look-solarized-dark
      - samba
      - silversearcher-ag
      - tmux
      - traceroute
      - tree
      - vim-gtk
      - wireshark
      - wmctrl
      - x11vnc
      - xclip
      - xdotool
      - xfonts-terminus
