- name: Install sysctl.d configuration
  become: true
  copy:
    src: sysctl.d/
    dest: /etc/sysctl.d/
    mode: 0644
    owner: root
    group: root
  notify: reload sysctl

- name: '.profile: define add_to_path function'
  blockinfile:
    dest: /home/{{ ansible_user_id }}/.profile
    marker: '# {mark} ANSIBLE: define add_to_path function'
    block: |
      add_to_path() {
          local DIR="$1"
          if [ -d "$DIR" ] && (echo ":$PATH:" | grep -qv ":$DIR:") ; then
              export PATH="$DIR:$PATH"
          fi
      }

- name: '.profile: update PATH with node, dotfiles, and home bin directories'
  blockinfile:
    dest: /home/{{ ansible_user_id }}/.profile
    marker: '# {mark} ANSIBLE: update PATH with node, dotfiles, and home bin directories'
    block: |
      add_to_path "$HOME/.n/bin"
      add_to_path "$HOME/.local/bin"
      add_to_path "$HOME/projects/dotfiles/bin"
      add_to_path "$HOME/bin"

- name: '.bashrc: HISTSIZE'
  lineinfile:
    path: /home/{{ ansible_user_id }}/.bashrc
    regexp: '^HISTSIZE=.*'
    line: 'HISTSIZE=10000'

- name: '.bashrc: HISTFILESIZE'
  lineinfile:
    path: /home/{{ ansible_user_id }}/.bashrc
    regexp: '^HISTFILESIZE=.*'
    line: 'HISTFILESIZE=20000'

- name: '.bashrc: configure GITHUB_TOKEN'
  blockinfile:
    dest: /home/{{ ansible_user_id }}/.bashrc
    marker: '# {mark} ANSIBLE: derive GitHub token'
    block: "export GITHUB_TOKEN=$(cat ~/.npmrc | grep '^//npm.pkg.github.com' | sed 's/^.*=\"\\(.*\\)\"/\\1/')"

- name: 'direnv: load in .bashrc'
  blockinfile:
    dest: /home/{{ ansible_user_id }}/.bashrc
    marker: '# {mark} ANSIBLE: load direnv'
    block: 'source <(direnv hook bash)'

- name: 'hosts: enable FQDN to enable sending via gmail'
  become: true
  blockinfile:
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE: enable FQDN to enable sending via gmail"
    block: "127.0.0.1  localhost.localdomain localhost {{ inventory_hostname }}"

- name: 'perf: disable kernel mitigations'
  become: true
  lineinfile:
    path: /etc/default/grub
    regexp: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet.*"'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash mitigations=off"'
  notify: update grub

- name: 'https: use Firefox except for Google Meets'
  block:
  - name: 'add browser-router as desktop application'
    copy:
      src: applications
      dest: /home/{{ ansible_user_id }}/.local/share/
      mode: 0644
    notify: update-desktop-database for user
  - name: 'register browser-router as https mime handler'
    community.general.gio_mime:
      mime_type: x-scheme-handler/https
      handler: browser-router.desktop

- name: Install common packages
  become: true
  block:

  - name: snap install
    community.general.snap:
      name:
        - localsend
      state: present

  - name: snap install
    community.general.snap:
      name:
        - dbeaver-ce
      classic: true
      state: present

  - name: Add non-free apt repositories
    become: true
    copy:
      src: apt
      dest: /etc
      mode: 0644
      owner: root
      group: root
    notify: update apt

  # by default, handlers are run after all tasks to avoid duplication, we need it now
  - name: Ensure update apt has run, if necessary
    meta: flush_handlers

  - name: apt install
    apt:
      state: present
      name:
        - apt-listchanges
        - autoconf
        - autogen
        - curl
        - direnv
        - dos2unix
        - dropbox
        # dmenu is required by dunst actions
        - dmenu
        - dunst
        - filezilla
        - fonts-liberation
        - fonts-noto-color-emoji
        - fonts-open-sans
        - g++
        - gh
        - git
        - git-delta
        - git-gui
        - gparted
        - google-chrome-stable
        - hexchat
        - inotify-tools
        - iotop
        - iperf3
        - jq
        - kubectl
        - libnotify-bin
        - make
        - meld
        - mitmproxy
        - nethogs
        - openssh-server
        - p7zip-full
        - pcmanfm
        - pkgconf
        - playerctl
        - postgresql-client
        - regolith-desktop
        - regolith-look-ayu
        - regolith-look-nord
        - remmina
        - samba
        - silversearcher-ag
        - spotify-client
        - tmate
        - tmux
        - traceroute
        - tree
        - ulauncher
        - uuid
        - vifm
        - vim-gtk3
        - vlc
        - vokoscreen-ng
        - wget
        - wireshark
        - wmctrl
        - x11vnc
        - xclip
        - xdotool
        - xfonts-terminus

  # we use dunst and don't know how to prevent installation above
  - name: apt remove regolith-rofication
    apt:
      state: absent
      name: regolith-rofication

  - name: apt install - xorg
    when: display_server == "xorg"
    apt:
      state: present
      name:
        - flameshot
        - i3xrocks-memory
        - i3xrocks-time
        - i3xrocks-volume
        - regolith-session-flashback

  - name: apt install - wayland
    when: display_server == "wayland"
    apt:
      state: present
      name:
        - regolith-session-sway
