- name: Install sysctl.d configuration
  become: true
  copy:
    src: sysctl.d/
    dest: /etc/sysctl.d/
    mode: 0644
    owner: root
    group: root
  notify: reload sysctl

- name: '.profile: include global node and dotfiles bins'
  blockinfile:
    dest: /home/{{ ansible_user_id }}/.profile
    marker: '# {mark} ANSIBLE: include global node and dotfiles bins'
    block: 'PATH="$PATH:$HOME/.n/bin:$HOME/projects/dotfiles/bin"'

- name: '.bashrc: configure GITHUB_TOKEN'
  blockinfile:
    dest: /home/{{ ansible_user_id }}/.bashrc
    marker: '# {mark} ANSIBLE: derive GitHub token'
    block: "export GITHUB_TOKEN=$(cat ~/.npmrc | grep '^//npm.pkg.github.com' | sed 's/^.*=\"\\(.*\\)\"/\\1/')"

- name: 'hosts: enable FQDN to enable sending via gmail'
  become: true
  blockinfile:
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE: enable FQDN to enable sending via gmail"
    block: "127.0.0.1	localhost.localdomain localhost {{ inventory_hostname }}"

- name: 'perf: disable kernel mitigations'
  become: true
  lineinfile:
    path: /etc/default/grub
    regexp: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet.*"'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash mitigations=off"'
  notify: update grub

- name: Install common packages
  become: true
  block:

  - name: Add non-free apt repositories
    become: true
    copy:
      src: apt
      dest: /etc
      mode: 0644
      owner: root
      group: root
    notify: update apt

  # by default, handlers are run after all tasks to avoid duplication, we need it now
  - name: Ensure update apt has run, if necessary
    meta: flush_handlers

  - name: apt install
    apt:
      state: present
      name:
        - apt-listchanges
        - autoconf
        - autogen
        - compizconfig-settings-manager
        - curl
        - dos2unix
        # dmenu is required by dunst actions
        - dmenu
        - dunst
        - filezilla
        - fonts-noto-color-emoji
        - g++
        - gconf2
        - git-gui
        - gparted
        - hexchat
        - hub
        - i3xrocks-volume
        - inotify-tools
        - iotop
        - jq
        - libnotify-bin
        - maim
        - make
        - meld
        - mesa-utils
        - mitmproxy
        - openssh-server
        - p7zip-full
        - pcmanfm
        - pkgconf
        - playerctl
        - regolith-desktop
        - samba
        - silversearcher-ag
        - spotify-client
        - tmux
        - traceroute
        - tree
        - vifm
        - vim-gtk3
        - wireshark
        - wmctrl
        - x11vnc
        - xclip
        - xdotool
        - xfonts-terminus
