- name: Install laptop packages
  become: true
  apt:
    state: present
    name:
      - fprintd
      - libpam-fprintd

      - i3xrocks-battery
      - xserver-xorg-input-synaptics

- name: Enable fingerprint on lock screen
  become: true
  copy:
    dest: /etc/pam.d/gnome-flashback
    owner: root
    group: root
    content: |
      # If we used https://gitlab.com/mishakmak/pam-fprint-grosshack.git, we'd
      # be able to use either finger or password without striking enter
      auth     requisite   pam_nologin.so
      auth     sufficient  pam_unix.so try_first_pass likeauth nullok
      auth     sufficient  pam_fprintd.so
      auth     optional    pam_gnome_keyring.so
      password required    pam_fprintd.so

- name: Configure synaptic touchpad
  become: true
  copy:
    src: xorg.conf.d/70-synaptics.conf
    dest: /etc/X11/xorg.conf.d/
    owner: root
    group: root
