- name: Install laptop packages
  become: true
  apt:
    state: present
    name:
      - i3xrocks-battery
      - i3lock
      - xss-lock
      - xserver-xorg-input-synaptics

- name: Configure synaptic touchpad
  become: true
  copy:
    src: xorg.conf.d/70-synaptics.conf
    dest: /etc/X11/xorg.conf.d/
    owner: root
    group: root
