#!/usr/bin/env ansible-playbook

- hosts: workstations
  roles:
    - role: workstation
      tags: workstation

- hosts: laptops
  roles:
    - role: laptop
      tags: laptop

- hosts: intel_graphics
  roles:
    - role: intel_graphics
      tags: intel_graphics
